server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/poliglota_sql?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update        # crea/actualiza las tablas autom치ticamente
    show-sql: true            # muestra las queries en consola
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  # --- Configuraci칩n MongoDB ---
  data:
    mongodb:
      uri: mongodb://localhost:27017/poliglota_mongo
      database : poliglota_mongo

  # --- Configuraci칩n Cassandra ---
  cassandra:
    contact-points: localhost
    port: 9042
    keyspace-name: poliglota_keyspace
    local-datacenter: datacenter1
    schema-action: create_if_not_exists
    request:
      timeout: 10s
    connection:
      connect-timeout: 10s
      init-query-timeout: 10s

# --- Configuraci칩n de logs ---
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: INFO
    com.poliglota: DEBUG
    org.springframework.data.cassandra: INFO
