server:
  port: 8080

# ===== PERFIL LOCAL (default) =====
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/poliglota?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: app
    password: app123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false          # üîπ si quer√©s, apag√° directamente el show-sql
    properties:
      hibernate:
        # Pod√©s incluso borrar el dialect para evitar warnings
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false

  data:
    mongodb:
      uri: mongodb://localhost:27017/poliglota

  cassandra:
    contact-points:
      - localhost
    port: 9042
    keyspace-name: poliglota
    local-datacenter: datacenter1
    schema-action: create_if_not_exists
    request:
      timeout: 10s
    connection:
      connect-timeout: 10s
      init-query-timeout: 10s

management:
  health:
    cassandra:
      enabled: true

logging:
  level:
    root: ERROR          # ‚¨Ö casi nada de ruido
    com.poliglota: INFO  # ‚¨Ö tus clases si usan logger

# ===== PERFIL "docker" (opcional, mismos hosts pero otro logging) =====
---
spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:mysql://localhost:3306/poliglota?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: app
    password: app123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false

  data:
    mongodb:
      uri: mongodb://localhost:27017/poliglota

  cassandra:
    contact-points:
      - localhost
    port: 9042
    keyspace-name: poliglota
    local-datacenter: datacenter1
    schema-action: create_if_not_exists
    request:
      timeout: 10s
    connection:
      connect-timeout: 10s
      init-query-timeout: 10s

management:
  health:
    cassandra:
      enabled: true

logging:
  level:
    root: ERROR
    com.poliglota: INFO
