version: '3.8'
services:
  mongo:
    image: mongo:6
    container_name: tp_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  cassandra:
    image: cassandra:4
    container_name: tp_cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=poliglota-cluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'DESCRIBE KEYSPACES'"]
      interval: 10s
      timeout: 5s
      retries: 30
volumes:
  mongo_data:
